% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{amsmath,amssymb}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={cameras data},
  pdfauthor={Acadia Berry},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{cameras data}
\author{Acadia Berry}
\date{2023-12-18}

\begin{document}
\maketitle

This data set represents a set of 28 cameras. Price is used to estimate
Consumer Reports Score. The units are dollars and points, respectively.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Import data set}

\NormalTok{Cameras }\OtherTok{\textless{}{-}} \FunctionTok{read.csv}\NormalTok{(}\StringTok{"Cameras.csv"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# make an ID field}
\CommentTok{\# first to last record}
\NormalTok{ID }\OtherTok{\textless{}{-}}\NormalTok{ Cameras}\SpecialCharTok{$}\NormalTok{ID }\OtherTok{\textless{}{-}} \DecValTok{1}\SpecialCharTok{:}\FunctionTok{nrow}\NormalTok{(Cameras)}

\CommentTok{\# summary statistics}
\FunctionTok{summary}\NormalTok{(Cameras)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##      Price           Score             ID       
##  Min.   : 80.0   Min.   :42.00   Min.   : 1.00  
##  1st Qu.:110.0   1st Qu.:52.00   1st Qu.: 7.75  
##  Median :160.0   Median :56.50   Median :14.50  
##  Mean   :175.4   Mean   :56.36   Mean   :14.50  
##  3rd Qu.:200.0   3rd Qu.:61.25   3rd Qu.:21.25  
##  Max.   :400.0   Max.   :66.00   Max.   :28.00
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{hist}\NormalTok{(Cameras}\SpecialCharTok{$}\NormalTok{Price)}
\end{Highlighting}
\end{Shaded}

\includegraphics{index_files/figure-latex/unnamed-chunk-3-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{hist}\NormalTok{(Cameras}\SpecialCharTok{$}\NormalTok{Score)}
\end{Highlighting}
\end{Shaded}

\includegraphics{index_files/figure-latex/unnamed-chunk-3-2.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# regress score on price}
\NormalTok{reg1 }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(Score }\SpecialCharTok{\textasciitilde{}}\NormalTok{ Price, }\AttributeTok{data =}\NormalTok{ Cameras) }
\FunctionTok{plot}\NormalTok{(reg1)}
\end{Highlighting}
\end{Shaded}

\includegraphics{index_files/figure-latex/unnamed-chunk-4-1.pdf}
\includegraphics{index_files/figure-latex/unnamed-chunk-4-2.pdf}
\includegraphics{index_files/figure-latex/unnamed-chunk-4-3.pdf}
\includegraphics{index_files/figure-latex/unnamed-chunk-4-4.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# coefficients for equation}
\FunctionTok{coefficients}\NormalTok{(reg1)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## (Intercept)       Price 
## 46.66880198  0.05524919
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# model summary}
\FunctionTok{summary}\NormalTok{(reg1)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = Score ~ Price, data = Cameras)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -11.8512  -1.7987   0.9775   3.3145   8.2814 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(>|t|)    
## (Intercept) 46.66880    2.23844  20.849  < 2e-16 ***
## Price        0.05525    0.01158   4.771 6.16e-05 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 4.982 on 26 degrees of freedom
## Multiple R-squared:  0.4668, Adjusted R-squared:  0.4463 
## F-statistic: 22.76 on 1 and 26 DF,  p-value: 6.155e-05
\end{verbatim}

Regression equation: \(y = 46.669 + 0.0552(x)\)

The estimated Score rating equals 46.669 points plus 0.0552 times the
dollar amount.

The slope of the regression equation indicates the estimated change in Y
per unit increase in X. For this regression, per every dollar amount
increase, the estimated change in Y is 0.0552.

In this regression equation \$ r\^{}2 = 0.4668 \$ is the proportion of
variability in score that is accounted for by price.

\(s = 4.982\) on 26 degrees of freedom. 4.982 represents the size of the
typical difference between the predicted value of scores and the actual
observed value of scores, with the unit expressed as scores.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# score rating by price}
\CommentTok{\# we can see a far removed point over 400 }
\FunctionTok{plot}\NormalTok{(Cameras}\SpecialCharTok{$}\NormalTok{Price, Cameras}\SpecialCharTok{$}\NormalTok{Score, }\AttributeTok{main=} \StringTok{"Score Rating by Price"}\NormalTok{,}
     \AttributeTok{xlab=} \StringTok{"Price"}\NormalTok{,}
     \AttributeTok{ylab=} \StringTok{"Score"}\NormalTok{)}
\FunctionTok{abline}\NormalTok{(reg1, }\AttributeTok{col=}\StringTok{"red"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{index_files/figure-latex/unnamed-chunk-5-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# residuals and standardized residuals}
\CommentTok{\# \# residuals = y{-}yhat}
\FunctionTok{rstandard}\NormalTok{(reg1) }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##           1           2           3           4           5           6 
##  0.24136876  1.69551664  0.37572346  0.87656090  1.10098297  0.67182197 
##           7           8           9          10          11          12 
##  0.46708304  1.26406194  1.05848339  0.46626538  0.07487333 -0.24796158 
##          13          14          15          16          17          18 
## -1.17729185  0.71596794 -0.05210046  0.67182197 -2.35747936  0.76308795 
##          19          20          21          22          23          24 
## -0.01250255  0.21373182 -0.90201257 -0.73864118 -0.17498790  0.19118693 
##          25          26          27          28 
## -0.22842198 -1.28656898 -1.60254350 -2.43635192
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{residuals}\NormalTok{(reg1)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##            1            2            3            4            5            6 
##   1.09896386   8.28135914   1.75643969   4.28135914   5.38634303   3.28135914 
##            7            8            9           10           11           12 
##   2.28135914   6.14880275   5.14880275   2.25378664   0.35877053  -1.19372142 
##           13           14           15           16           17           18 
##  -5.64122947   3.41391553  -0.24356031   3.28135914  -9.76847975   3.70129469 
##           19           20           21           22           23           24 
##  -0.06116503   1.04381886  -4.37611670  -3.61365697  -0.85119725   0.91126247 
##           25           26           27           28 
##  -1.08873753  -6.19372142  -7.74621336 -11.85119725
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{reg1}\SpecialCharTok{$}\NormalTok{residuals[}\DecValTok{28}\NormalTok{]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##       28 
## -11.8512
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{reg1}\SpecialCharTok{$}\NormalTok{residuals[}\DecValTok{17}\NormalTok{]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##       17 
## -9.76848
\end{verbatim}

In this regression, outliers are defined to be the observations whose
absolute value of standardized residual exceeds 2. The score of -2.357
for observation number 17 exceeds the threshold of 2 and the score of
observation 28 with a score of -2.436, respectively. Observation 17's
has a residual score of -9.768. The true score of 59 points for
observation 17 is much lower than its predicted score of 68.768, given
its price of 400 dollars. Observation 28 has a residual score of
-11.851. The original score of observation 28 of 42 points is much lower
than the predicted score of 53.851, given its price point at 130
dollars.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# High{-}leverage values}

\CommentTok{\# plot for leverage values}
\FunctionTok{plot}\NormalTok{(}\FunctionTok{hatvalues}\NormalTok{(reg1), }\AttributeTok{type =} \StringTok{"h"}\NormalTok{, }\AttributeTok{xlab=} \StringTok{"Index"}\NormalTok{, }\AttributeTok{ylab=} \StringTok{"Leverage values"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{index_files/figure-latex/unnamed-chunk-6-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# list of leverage values}
\FunctionTok{hatvalues}\NormalTok{(reg1)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##          1          2          3          4          5          6          7 
## 0.16491404 0.03899512 0.11964806 0.03899512 0.03583074 0.03899512 0.03899512 
##          8          9         10         11         12         13         14 
## 0.04682887 0.04682887 0.05879175 0.07507670 0.06639396 0.07507670 0.08410674 
##         15         16         17         18         19         20         21 
## 0.11964806 0.03899512 0.30835279 0.05227005 0.03586933 0.03918807 0.05184556 
##         22         23         24         25         26         27         28 
## 0.03583074 0.04682887 0.08483995 0.08483995 0.06639396 0.05879175 0.04682887
\end{verbatim}

Observation 17 has a leverage value of 0.308, the largest of all
leverage values. As shown in the plot below, the point above 17 is
extremely high in comparison to the rest of the points. One can conclude
observation 17 is a high leverage point. A high leverage point is a
value that is extreme in the X space. In this regression analysis, a
high leverage point would be a value indicating a very low or very high
price in comparison to the rest of the price data. In this case,
observation 17 is a camera with a very high price.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Influential Observations}

\CommentTok{\# Cooks distance}
\CommentTok{\# df2 = n{-}m{-}1 = 28{-}1{-}1 = 26}

\CommentTok{\# to find median of F distribution with 1 and 26 DF}
\FunctionTok{qf}\NormalTok{(}\FloatTok{0.5}\NormalTok{,}\DecValTok{1}\NormalTok{,}\DecValTok{26}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.4679148
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# for 25th percentile, any between 25th and 50th are tending}
\FunctionTok{qf}\NormalTok{(}\FloatTok{0.25}\NormalTok{,}\DecValTok{1}\NormalTok{,}\DecValTok{26}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.1037076
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{sort}\NormalTok{(}\FunctionTok{cooks.distance}\NormalTok{(reg1)) }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##           19           15           11           23           20           24 
## 2.907732e-06 1.844601e-04 2.275222e-04 7.521922e-04 9.315879e-04 1.694298e-03 
##           12           25            7            1           10            6 
## 2.186270e-03 2.418517e-03 4.426320e-03 5.752526e-03 6.789957e-03 9.157208e-03 
##           16            3           22            4           18           21 
## 9.157208e-03 9.593034e-03 1.013770e-02 1.558902e-02 1.605785e-02 2.224476e-02 
##            5           14            9            8           13            2 
## 2.252339e-02 2.353657e-02 2.752206e-02 3.925089e-02 5.625197e-02 5.832554e-02 
##           26           27           28           17 
## 5.885740e-02 8.020849e-02 1.458119e-01 1.238879e+00
\end{verbatim}

Cooks distance was calculated to identify the threshold for influential
observations. Any values calculated with Cooks Distance above 0.4679 are
considered influential. The cutoff for Cook's distance scores at the
25th percentile is 0.1037 and at the 50th percentile is 0.468.

Observation 17 has a leverage value of 0.308, a residual score of -9.768
and a standardized residual value of greater than 2 (-2.357), and a
Cook's distance score of 01.239 making it an outlier. Observation 17
exceeds the F-median value of 0.468 at of 1.239 and is statistically
influential.

Observation 28 has a leverage value of 0.047 and standardized residual
value of -2.436. Due to its absolute residual value being over 2, it is
considered an outsider. Observation 28 has a Cook's distance score of
0.146. It falls between the F-25th and F-median value, meaning it is
tending toward influential. All other observations are not statistically
influential.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# verify assumptions}

\FunctionTok{par}\NormalTok{(}\AttributeTok{mfrow=} \FunctionTok{c}\NormalTok{(}\DecValTok{2}\NormalTok{,}\DecValTok{2}\NormalTok{)); }\FunctionTok{plot}\NormalTok{(reg1, }\AttributeTok{pch=}\DecValTok{19}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{index_files/figure-latex/unnamed-chunk-8-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#plot(reg1)}
\end{Highlighting}
\end{Shaded}

The independence, constant variance, zero mean, and normality
assumptions are verified through analysis of the Residuals vs Fitted
plot and Normal Q-Q plot. The pattern of the Residuals vs Fitted
scatterplot does not seem to increase from left to right, therefore the
zero mean assumption is verified. There is no obvious curvature in the
pattern, which verifies the independence assumption. It could be argued
the Residual vs Fitted plot displays a funnel pattern which would
violate the constant variance assumption, even with observation 28 and
observation 17 out of the picture (observations which were already
confirmed to be influential or tending toward influential), but this
assertion is not conclusive. The normal Q-Q plot shows the bulk of the
residuals lie near the straight line on the plot, aside from observation
28 and observation 17. In the bottom left of the plot, the points seem
to dip below the line, but besides this, the normality assumption is
verified.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{summary}\NormalTok{(reg1)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = Score ~ Price, data = Cameras)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -11.8512  -1.7987   0.9775   3.3145   8.2814 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(>|t|)    
## (Intercept) 46.66880    2.23844  20.849  < 2e-16 ***
## Price        0.05525    0.01158   4.771 6.16e-05 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 4.982 on 26 degrees of freedom
## Multiple R-squared:  0.4668, Adjusted R-squared:  0.4463 
## F-statistic: 22.76 on 1 and 26 DF,  p-value: 6.155e-05
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
    \CommentTok{\#p value: 6.16e{-}05, is very small }
     \CommentTok{\# b0 ( y int) = 46.66880}
     \CommentTok{\# b1 (slope) = 0.05525}
     \CommentTok{\# sb1 (error) = 0.01158}
     \CommentTok{\# t (test of b1/sb1)= 4.771}
\end{Highlighting}
\end{Shaded}

Regression equation:
\(𝑦̂ = 46.66880 + 0.05525(𝑥), 𝑡 = 4.771, p = 6.16e-05\)

Null and alternative hypotheses: \(H_0: 𝛽1 = 0\): no linear relationship
exists between Score and Price \(H_a: 𝛽1 ≠ 0\): linear relationship
exists between Score and Price

The p-value (6.16e-05) for the t-test result (4.771) is very small,
therefore, we reject the null hypothesis of \(H_0: 𝛽1 = 0\) and conclude
that a linear relationship does exist between Score and Price
(\(H_a: 𝛽1 ≠ 0\)).

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# 95\% prediction interval for $250 camera}
\NormalTok{camera250 }\OtherTok{\textless{}{-}}\FunctionTok{data.frame}\NormalTok{(}\AttributeTok{Price=}\DecValTok{250}\NormalTok{)}
\FunctionTok{predict}\NormalTok{(reg1, camera250, }\AttributeTok{interval =} \StringTok{"prediction"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##       fit      lwr      upr
## 1 60.4811 49.90802 71.05418
\end{verbatim}

There is 95\% confidence that the score of a camera with a price of 250
dollars lies between 49.91 and 71.05 points.

\end{document}
